### ISSUE TITLE
New Version 2.7 - QGIS does not start from within the Config Manager

### ISSUE THREAD

**Issue by LucJBJanssens** [roam-qgis/Roam#417]
Hi,
after a fresh install (removed old folder and installed 2.7)
"Open in QGIS in Roam Config Manager" results in following error

**Something has gone wrong.
Error: UnboundLocalError: local variable 'qgislocation' referenced before assignment
Traceback (most recent call last):
  File "configmanager\ui\projectwidget.pyc", line 259, in openinqgis
  File "configmanager\utils.pyc", line 56, in openqgis
UnboundLocalError: local variable 'qgislocation' referenced before assignment**

"Add layers in QGIS in Roam Config Manager" results in following error
**Something has gone wrong.
Error: UnboundLocalError: local variable 'qgislocation' referenced before assignment
Traceback (most recent call last):
  File "configmanager\ui\layerwidgets.pyc", line 859, in open_qgis
  File "configmanager\utils.pyc", line 56, in openqgis
UnboundLocalError: local variable 'qgislocation' referenced before assignment**

I checked the QGIS path and parsed this commandline in the Windows Shell ... QGIS starts flawlessly from the Windows shell

Regards
An avid IntraMaps Roam user

**Comment by TKGRAH** [comment]
I am also receiving this error. 2.6 works fine for me. I am a new user, so I would like to use the latest, but I could not figure out how to fix it on my end.
